algorithm: sac
algorithm_kwargs:
  batch_size: 256
  max_path_length: 80
  min_num_steps_before_training: 1000
  num_epochs: 1000
  num_eval_steps_per_epoch: 1000
  num_expl_steps_per_train_loop: 1000
  num_trains_per_train_loop: 1000
archi: pointnet
env_name: SShape-Boxes-1024Pts-SurfaceNormals-v0
log_dir: /home/yixuan/sshape_boxes_global_1024/seed1
mode: her
policy_kwargs:
  hidden_dim: 256
  n_layers: 3
qf_kwargs:
  hidden_dim: 256
  n_layers: 3
replay_buffer_kwargs:
  fraction_goals_env_goals: 0
  fraction_goals_rollout_goals: 0.19999999999999996
  max_replay_buffer_size: 1000000
resume: false
seed: 1
trainer_kwargs:
  alpha: 0.1
  discount: 0.99
  policy_lr: 0.0003
  qf_lr: 0.0003
  reward_scale: 1.0
  soft_target_tau: 0.005
  target_update_period: 1
  use_automatic_entropy_tuning: true
version: normal
